Add homepage entry for NGINX Gateway Fabric
nginx/nginx.org pull request #107
Opened 2024-11-13 20:20 UTC by sjberman

2024-11-14 15:19 UTC, lcrilly commented on xml/homepage.xml
> +  description="NGINX Gateway Fabric provides an implementation for the Gateway API using NGINX as the data plane."
Some mention of Kubernetes would be useful. Gateway API is not a universally recognised term.

2024-11-27 21:41 UTC, lcrilly requested changes
Looks good, but please adjust the commit message as per the [style guide](https://github.com/nginx/nginx.org?tab=readme-ov-file#style-guide). Needs a full stop.

2024-11-27 22:10 UTC, lcrilly approved these changes

2024-11-27 22:29 UTC, sjberman commented
I don't have permission to merge.

2024-11-28 09:25 UTC, merged