fixes broken link for Admin's Guide
nginx/nginx.org pull request #24
Opened 2024-05-22 13:43 UTC by Robb-Fr

This current link to Admin's Guide (https://www.nginx.com/resources/admin-guide/) leads to a 404 not found web page. This new link (https://docs.nginx.com/nginx/admin-guide/) seems to be the intended destination.

2024-05-22 14:06 UTC, y82 requested changes
Hi @Robb-Fr,

Thank you for your patch, it is good. 

However, according to our styleguide (see README.md):
- changelog still needs to be adjusted, for example, "Fixed broken link for Admin's Guide." (Past tense, full stop in the end, capital letter in the beginning)
- file version should be bumped to 52:  rev="52"
- as it is not a language-related change, it would be also nice to fix it in the existing localizations wherever it exists, currently only for /ru/docs/index.xml
- When implementing the feedback, please keep in mind that the review feedback should implemented into the same patch. Do not include a separate patch with the review in the PR.(The PRs are added as "Rebase and merge" option.)
And thank you again for the patch.

2024-05-22 14:35 UTC, Robb-Fr commented
Hello @y82 !
Thanks a lot for your detailed and kind feedback. If I understood it correctly, the required changed should be implemented!
Sorry for missing the style guide, let me know if I missed something.

2024-05-22 15:48 UTC, y82 commented
Hi @Robb-Fr,

Thank you for implementing the feedback - it's all correct except 1 style comment, see README.md:
"Review feedback is implemented into the same patch, do not include a separate patch with the review in the PR. "
In other words, the current rule is 1patch inside 1pr. So you need to merge the 3 patches into 1 with the commit log "Fixed broken link for Admin's Guide."

2024-05-23 06:14 UTC, Robb-Fr commented
Hey @y82 
Sorry for misunderstanding this part, I think I finally got it! Let me know if anything else is missing. Thanks for your time!

2024-05-23 07:35 UTC, merged

2024-05-23 07:38 UTC, y82 commented
Hi @Robb-Fr,
Thank you, all good now, the patch was committed to the repo.