Development guide: updated the link to nginx-dev-examples repository.
nginx/nginx.org pull request #73
Opened 2024-09-16 23:25 UTC by thresheek

2024-09-17 11:06 UTC, pluknet requested changes
it makes sense to replace all such links altogether
```
diff --git a/xml/en/docs/dev/development_guide.xml b/xml/en/docs/dev/development_guide.xml
index 112d2ea1..f3eca976 100644
--- a/xml/en/docs/dev/development_guide.xml
+++ b/xml/en/docs/dev/development_guide.xml
@@ -7657,14 +7657,14 @@ requests, but may contain other nginx directives.
 An example of such approach is the
 <link doc="../http/ngx_http_auth_request_module.xml" id="auth_request"/>
 directive implemented in
-<link url="http://hg.nginx.org/nginx/file/tip/src/http/modules/ngx_http_auth_request_module.c">ngx_http_auth_request module</link>.
+<link url="https://github.com/nginx/nginx/blob/master/src/http/modules/ngx_http_auth_request_module.c">ngx_http_auth_request module</link>.
 </para>
 
 <para>
 For the second case, it is possible to use basic HTTP client functionality
 available in nginx.
 For example,
-<link url="http://hg.nginx.org/nginx/file/tip/src/event/ngx_event_openssl_stapling.c">OCSP module</link>
+<link url="https://github.com/nginx/nginx/blob/master/src/event/ngx_event_openssl_stapling.c">OCSP module</link>
 implements simple HTTP client.
 </para>
 
```

2024-09-17 18:06 UTC, thresheek commented
Oh, good catch.  Updated, and changed commit message to:

"Development guide: updated the links to reflect projects move to Git."

2024-09-17 22:09 UTC, pluknet approved these changes
Looks good, tnx.

2024-09-19 07:38 UTC, y82 approved these changes

2024-09-19 10:52 UTC, merged