Restructured text in syntax.xml.
nginx/nginx.org pull request #88
Opened 2024-10-04 16:15 UTC by y82

The main goal of this patch is to make visible the "A value without a suffix means seconds." sentence. While here, I also tried to structure the text and make it more readable.

2024-10-04 16:37 UTC, lcrilly commented
Suggest adding `(default)` to the `s` unit (line 62).

2024-10-07 15:27 UTC, pluknet commented on xml/ru/docs/syntax.xml
> +Оффсеты также можно указать в гигабайтах используя
отступы? смещения?

2024-10-07 19:20 UTC, pluknet requested changes

2024-10-07 19:20 UTC, pluknet commented on xml/en/docs/syntax.xml
> +<section id="combine" name="Combining multiple units">
This section discusses time intervals only.
Does it make sense to combine it with previous section?

2024-10-07 19:20 UTC, pluknet commented on xml/en/docs/syntax.xml
>  A value without a suffix means seconds.
See previous comment.
Either it should be merged with previous section, or this line is wrong for size/offset.

2024-10-08 11:52 UTC, pluknet approved these changes

2024-10-09 09:00 UTC, merged